Resources:
  PostgresForEC2:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: True
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: postsEC2
      DBName: postsEC2
      DBParameterGroupName: default.postgres10
      DBSecurityGroups:
        - sg-7fc8b833
      DBSubnetGroupName: default
      Engine: postgres
      EngineVersion: 10.4
      MasterUsername: serverapi
      MasterUserPassword: serverapi
      MultiAZ: False
      Port: 5432
      PubliclyAccessible: True
      StorageType: standard
      VPCSecurityGroups:
        - sg-7fc8b833
