Parameters:
  apiType:
    Type: String
    AllowedValues:
      - ec2
      - lambda

Resources:
  PostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: True
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: !Join
        - ''
        - - !Ref apiType
          - postsdb
      DBName: !Join
        - ''
        - - !Ref apiType
          - postsdb
      DBParameterGroupName: default.postgres10
      DBSubnetGroupName: default
      Engine: postgres
      EngineVersion: 10.4
      MasterUsername: serverless
      MasterUserPassword: serverless
      MultiAZ: False
      Port: 5432
      PubliclyAccessible: True
      StorageType: standard
      VPCSecurityGroups:
        - sg-7fc8b833

Outputs:
  dbAddress:
    Description: URL of the database endpoint address
    Value: !GetAtt PostgresDB.Endpoint.Address
  dbPort:
    Description: port of the database endpoint
    Value: !GetAtt PostgresDB.Endpoint.Port

